services:
  - type: web
    name: amopoint
    env: docker
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://amopoint.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: amopoint-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: amopoint-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: amopoint-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: amopoint-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: amopoint-db
          property: password
      - key: STATS_USER
        value: admin
      - key: STATS_PASS
        value: admin

databases:
  - name: amopoint-db
    plan: free
